SIDDHANT SINHA

25070123109

EXP10: STUDY OF PANDAS LIBRARY

In [64]:
# Introduction to Pandas
# Pandas: Panel Data
'''Used for:
Structured data
EDA
Data Cleaning'''
#you can use display, print or if you want to print it directly then you need to move to new cell or it runs the last command and not others

'Used for:\nStructured data\nEDA\nData Cleaning'

In [65]:
import pandas as pd
s=pd.Series([10,20,30,40])       # panda.series command converts it into rows 0th row has 10, 1st row has 20 etc etc..
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [66]:
#Create DataFrame
data={                              #stored in dictionary
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df= pd.DataFrame(data)              # used to convert data ito tabular form
print(df)

  Name  Marks
0    A     85
1    B     90
2    C     78

In [67]:
print(df.head())                           #prints first 5 rows
print(df.tail())                           #prints last 5 rows
print(df.head(2))                          #prints first 2 rows
print(df.tail(2))                          #prints last 2 rows

  Name  Marks
0    A     85
1    B     90
2    C     78
  Name  Marks
0    A     85
1    B     90
2    C     78
  Name  Marks
0    A     85
1    B     90
  Name  Marks
1    B     90
2    C     78

In [68]:
# Find the structure of the DataFrame
print(df.shape)                         #gives you the no. of rows and colums

(3, 2)

In [69]:
#Dimensions
print(df.ndim)                          # 2 dimension as it has only name and marks i.e total no. of variables/parameters.

2

In [70]:
print(df.size)                         #total number of elements

6

In [71]:
#Display Column Names
print(df.columns)

Index(['Name', 'Marks'], dtype='object')

In [72]:
#Check Data Type of each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [73]:
#Access Individual Column
print(df["Name"])
df["Name"]
display(df["Name"])

0    A
1    B
2    C
Name: Name, dtype: object

0    A
1    B
2    C
Name: Name, dtype: object

In [74]:
#Access specific row
df.loc[1]                       #prints 2nd row as it has indexing 1 so it prints a specific row

Name      B
Marks    90
Name: 1, dtype: object

In [75]:
# loc and iloc are different as to print 1st row 2nd column type of things can be printed by iloc
df.iloc[1,1]

np.int64(90)

In [76]:
#Add a New Column
'''If marks 80-90- First Class
If marks>=90- Distinction
If marks >80- Second Class'''
df["Grade"]=["First class","Distinction","Second Class"]          #used to add a new column and adds it in the sequence you've typed it in.
df                                                                #prints df

  Name  Marks         Grade
0    A     85   First class
1    B     90   Distinction
2    C     78  Second Class

In [77]:
#Update data in DataFrame
#Change marks of student A to 88.
df.loc[0,"Marks"]= 81
df
df.iloc[0,1]=81
df

  Name  Marks         Grade
0    A     81   First class
1    B     90   Distinction
2    C     78  Second Class

In [78]:
#Delete a Column
df1=df.drop("Grade",axis=1)
display(df1)
display(df)

  Name  Marks
0    A     81
1    B     90
2    C     78

  Name  Marks         Grade
0    A     81   First class
1    B     90   Distinction
2    C     78  Second Class

In [80]:
#Perform Basic Statistical Analysis
mean1=df["Marks"].mean()
mean1

np.float64(83.0)

In [82]:
max1=df["Marks"].max()
print(max1)
min1=df["Marks"].min()
print(min1)

90
78

In [83]:
#Apply Condition(filtering)
#Display students scoring more than 80
df[df["Marks"] > 80]

  Name  Marks        Grade
0    A     81  First class
1    B     90  Distinction